### ISSUE TITLE
Can't run "npm run test"

### ISSUE THREAD

**Issue by alastor0325** [alastor0325/autoplay-shield-study#1]
The following is the log when running "$npm run test:unit"

---

START:
26 07 2018 14:46:47.203:INFO [karma]: Karma v2.0.3 server started at http://0.0.0.0:9877/
26 07 2018 14:46:47.206:INFO [launcher]: Launching browser FirefoxNightly with unlimited concurrency
26 07 2018 14:46:47.209:INFO [launcher]: Starting browser FirefoxNightly
26 07 2018 14:47:47.215:WARN [launcher]: FirefoxNightly have not captured in 60000 ms, killing.
26 07 2018 14:47:49.217:WARN [launcher]: FirefoxNightly was not killed in 2000 ms, sending SIGKILL.
26 07 2018 14:47:51.219:WARN [launcher]: FirefoxNightly was not killed by SIGKILL in 2000 ms, continuing.

Finished in 0 secs / 0 secs @ 14:47:51 GMT-0700 (Pacific Daylight Time)

26 07 2018 14:47:51.225:ERROR [karma]: TypeError: Cannot read property 'files' of undefined
    at toInitialList (/Users/awu/projects/web-extensions/template-shield/node_modules/istanbul-lib-report/lib/summarizer.js:147:17)
    at Object.createPackageSummary [as pkg] (/Users/awu/projects/web-extensions/template-shield/node_modules/istanbul-lib-report/lib/summarizer.js:240:21)
    at IstanbulReporter.onRunComplete (/Users/awu/projects/web-extensions/template-shield/node_modules/karma-istanbuljs-reporter/index.js:40:38)
    at Server.<anonymous> (/Users/awu/projects/web-extensions/template-shield/node_modules/karma/lib/events.js:39:26)
    at Server.emit (events.js:187:15)
    at emitRunCompleteIfAllBrowsersDone (/Users/awu/projects/web-extensions/template-shield/node_modules/karma/lib/server.js:256:14)
    at Server.on (/Users/awu/projects/web-extensions/template-shield/node_modules/karma/lib/server.js:292:9)
    at Server.emit (events.js:182:13)
    at Object.BaseLauncher._done (/Users/awu/projects/web-extensions/template-shield/node_modules/karma/lib/launchers/base.js:112:15)
    at /Users/awu/projects/web-extensions/template-shield/node_modules/karma/lib/launchers/process.js:134:12
    at next (/Users/awu/projects/web-extensions/template-shield/node_modules/rimraf/rimraf.js:75:7)
    at CB (/Users/awu/projects/web-extensions/template-shield/node_modules/rimraf/rimraf.js:111:9)
    at FSReqWrap.oncomplete (fs.js:145:20)
(node:37538) [DEP0079] DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated

**Comment by alastor0325** [comment]
In addition, every time the console shows 
```
26 07 2018 14:49:50.807:INFO [launcher]: Starting browser FirefoxNightly
```
Then the console would stuck at that line and FirefoxNightly doens't be exercuted.
